#!/usr/bin/env bash
# Script installs nginx when executed and opens port 80

sudo ufw allow 22;
sudo apt-get install -y nginx && sudo ufw allow 'Nginx HTTP';
sudo chown -R "$USER:$USER" /var/www/html
sudo chmod -R 755 /var/www/html/index.html
