#!/usr/bin/env bash
# Script to configure server to redirect 301 moved permanently

sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start
sudo chown -R "$USER:$USER" /var/www/html
sudo chmod -R 755 /var/www/html
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "s/^server {/server {\n\trewrite \^\/redirect_me\/\(.*\)$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4\$1 permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
