#!/usr/bin/env bash
# Script to configure server to redirect 301 moved permanently

sudo apt-get -y update
sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i "s/http {/http {\n\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/nginx.conf
sudo service nginx restart
