#!/usr/bin/env bash
# This script displays "Best School" 10 times but display
# "Hi" on the next line after the 9th iteraction

i=1
while (( i <= 10 ))
do
	echo "Best School"
	if (( i == 9 ))
	then
		echo "Hi"
	fi
	(( i++ ))
done
