#!/usr/bin/env bash
# This script displays "bad luck" on the forth line
# displays "good luck" on the eight line
# "Best School" on the rest of the lines
i=1
while [[ "$i" -lt 11 ]]
do
	if [[ "$i" -eq 4 ]]
	then
		echo "bad luck"
	elif [[ "$i" -eq 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
