#!/usr/bin/env bash
# This script displays time from 0 to 12 hours and
# minutes from 0 to 59
i=0
while [[ "$i" -lt 13 ]]
do
	echo "Hour: $i"
	j=1
	while [[ "$j" -lt 60 ]]
	do
	    echo "$j"
	    j=$(( j+1 ))
	done
	i=$(( i+1 ))
done
