#!/usr/bin/env bash
# Script lists all active IPs on the machine executing it

addresses=$(hostname -I)
IFS=" " read -r -a addresses <<< "$addresses"
# addresses=(${addresses//" "/})

for ip in "${addresses[@]}"
do
	echo "$ip"
done
