#!/usr/bin/env bash
# Debug the machine get apache running and
#+return 'Hello Holberton' when accessed
#+using curl on port 80

service apache2 start
sed -i 's/80/8080/' /etc/apache2/ports.conf
sed -i 's/80/8080/' /etc/apache2/sites-available/000-default.conf
